name = "PkgTemplateXKDR"
uuid = "1db85fae-a281-4a81-a703-9f9ee6e4abbb"
authors = ["Siddhant Chaudhary", "xKDR Forum"]
version = "0.1.0"

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"

[compat]
PkgTemplates = "0.7"
julia = "1"
